release:
  prepare:
    - "@semantic-release/changelog"
    - "@semantic-release/npm"
    - "@semantic-release/git"
  verifyConditions:
    - "@semantic-release/changelog"
    - "@semantic-release/npm"
    - "@semantic-release/git"
